# Generated by Django 5.1.2 on 2025-08-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="quantity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
