# Generated by Django 5.1.2 on 2025-10-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='レシピ名')),
                ('catch_copy', models.CharField(blank=True, max_length=255, null=True)),
                ('main_ingredients', models.TextField(default='', verbose_name='主要な食材')),
                ('nutrients', models.TextField(default='', verbose_name='摂取できる栄養素')),
                ('cooking_point', models.TextField(default='', verbose_name='調理のポイント')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_images/', verbose_name='料理画像')),
                ('ingredients', models.TextField(verbose_name='材料リスト')),
                ('instructions', models.TextField(verbose_name='作り方の手順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
        ),
    ]
