# Generated by Django 5.1.2 on 2025-10-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_delete_recipe_ingredient_expiry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='expiry_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
