# Generated by Django 5.1.2 on 2025-10-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_alter_ingredient_expiry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='expiry_type',
            field=models.CharField(blank=True, choices=[('賞味期限', '賞味期限'), ('消費期限', '消費期限')], max_length=10, null=True, verbose_name='期限の種類'),
        ),
    ]
